### ISSUE TITLE
Any guide?

### ISSUE THREAD

**Issue by omarsar** [Guillem-db/PyData-Bcn-2017#1]
Great work and nice presentation on PyData. :+1: 
Is there any plan to create a short guide on how to use your code. There seems some part that can be reused to build other different types of models.

**Comment by Guillemdb** [comment]
Thank you, I'm glad you liked it! 
There was no plan because you are the first person interested in this code, but I will be glad to help with everything I can. Are you planing on using it for anything specific? What are the parts that you would like to reuse? I can try to write a more reusable and commented version of whatever you need :)

**Comment by omarsar** [comment]
@Guillem-db Thanks for the fast response. I am taking a look at your ipython notebooks first and see if I can follow the code. Wherever I need your assistance I will contact you. I will fork your repo for now and test on my machine. Thanks and awesome work again!
